apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: boutique-pod-crashlooping
  namespace: monitoring
  labels:
    release: kps
spec:
  groups:
    - name: boutique.rules
      rules:
        - alert: BoutiquePodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total{namespace="boutique"}[10m]) > 2
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} in boutique is restarting"
            description: "Container {{ $labels.container }} has restarted more than twice in 10m."