apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/mabdullahmuzaffar/online-shopping-store-devops.git
    targetRevision: main
    path: charts/boutique
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: services.frontend.type
          value: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true