apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
    {{- include "boutique.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.cartservice.replicas }}
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
        {{- include "boutique.selectorLabels" (dict "root" . "name" "cartservice") | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: {{ include "boutique.image" (dict "root" . "name" "cartservice") | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.cartservice.containerPort }}
          env:
            {{- range $k, $v := .Values.services.cartservice.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          readinessProbe:
            initialDelaySeconds: 15
            grpc:
              port: {{ .Values.services.cartservice.containerPort }}
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            grpc:
              port: {{ .Values.services.cartservice.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
    {{- include "boutique.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
    - name: grpc
      port: {{ .Values.services.cartservice.servicePort }}
      targetPort: {{ .Values.services.cartservice.containerPort }}
