{{- $redis := index .Values.services "redis-cart" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    app: redis-cart
    {{- include "boutique.labels" . | nindent 4 }}
spec:
  replicas: {{ $redis.replicas }}
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
        {{- include "boutique.selectorLabels" (dict "root" . "name" "redis-cart") | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: redis
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: {{ $redis.image | quote }}
          ports:
            - containerPort: {{ $redis.containerPort }}
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: {{ $redis.containerPort }}
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: {{ $redis.containerPort }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              cpu: 70m
              memory: 200Mi
            limits:
              cpu: 125m
              memory: 256Mi
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  labels:
    app: redis-cart
    {{- include "boutique.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
    - name: tcp-redis
      port: {{ $redis.servicePort }}
      targetPort: {{ $redis.containerPort }}