{{- range $name, $svc := .Values.services }}
{{- if or (eq $name "frontend") (eq $name "cartservice") (eq $name "redis-cart") }}
{{- else }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ $svc.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: "{{ $.Values.image.registry }}/{{ $name }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: {{ $svc.containerPort }}
          env:
            {{- if eq $name "checkoutservice" }}
            {{- range $k, $v := $.Values.checkoutEnv }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- else if $svc.env }}
            {{- range $k, $v := $svc.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- end }}
          readinessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: {{ $svc.containerPort }}
          livenessProbe:
            periodSeconds: 10
            tcpSocket:
              port: {{ $svc.containerPort }}
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $name }}
  ports:
    - name: grpc
      port: {{ $svc.servicePort }}
      targetPort: {{ $svc.containerPort }}
{{- end }}
{{- end }}
